# Generated by Django 5.2.5 on 2026-01-31 10:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cube_type', models.CharField(choices=[('2x2', '2x2'), ('3x3', '3x3'), ('4x4', '4x4'), ('pyraminx', 'Пираминкс')], default='2x2', max_length=20)),
                ('scramble', models.CharField(max_length=200)),
                ('solve_time', models.FloatField()),
                ('solved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rubik_timer_solve',
                'ordering': ['-solved_at'],
            },
        ),
    ]
